config/routes.rb
Rails.application.routes.draw do
  # constraints(host: /graphgist-portal.herokuapp.com/) do
  #   match '/(*path)' => redirect { |params, _req| "http://portal.graphgist.org/#{params[:path]}" }, via: [:get, :post]
  # end

  mathjax 'mathjax'

  root 'info#home'
  get 'about' => 'info#about'

  get 'featured_graphgists.json' => 'info#featured_graphgists_json'
  get 'featured_graphgists(.:format)' => 'info#featured_graphgists'

  get 'submit_graphgist' => 'info#submit_graphgist'

  get 'submit_challenge_entry' => 'info#submit_challenge_entry'

  post 'preview_graphgist' => 'info#preview_graphgist'
  get 'preview_graphgist/:id' => 'info#preview_graphgist'
  patch 'preview_graphgist/:id' => 'info#preview_graphgist'

  get 'monitor' => 'info#monitor'

  authenticated do
    post 'create_graphgist' => 'info#create_graphgist'
    get 'my_graphgists' => 'info#my_graphgists'
  end

  get 'challenge_graphgists' => 'info#challenge_graphgists'

  get 'render_graphgist' => 'info#render_graphgist'

  get 'graph_gists/by_graphgist_id/*id(.:format)' => 'info#show_from_graphgist_id'
  get 'graph_gists/by_graphgist_id(.:format)' => 'info#show_from_graphgist_id'
  get 'graph_gists/by_url' => 'info#show_from_url'
  get 'graph_gists/new' => redirect('submit_graphgist')
  # Deprecated:
  get 'show_from_graphgist_id/:id(.:format)' => 'info#show_from_graphgist_id'

  match 'graph_gists/:id_or_slug/graph_guide' => 'info#graph_guide_options', via: :options
  get 'graph_gists/:id_or_slug/graph_guide' => 'info#graph_guide', as: :graph_guide

  get 'graph_gists/:id/edit_by_owner' => 'assets#edit_graph_gists_by_owner', as: :graph_edit_by_owner
  patch 'graph_gists/:id/edit_by_owner' => 'assets#update_graph_gists_by_owner', as: :graph_update_by_owner

  get 'graph_gists/:id/edit_by_owner_step2' => 'assets#edit_graph_gists_by_owner_step2', as: :graph_edit_by_owner_step2
  patch 'graph_gists/:id/edit_by_owner_step2' => 'assets#update_graph_gists_by_owner_step2', as: :graph_update_by_owner_step2

  get 'graph_gists/:id/source' => 'assets#show_source', as: :graph_show_source

  get 'candidates/waiting_review' => 'info#list_candidates', as: :list_candidates_graphgist
  post 'candidates/graphgist/:id/status/live' => 'assets#make_graphgist_live', as: :make_graphgist_live
  post 'candidates/graphgist/:id/status/disabled' => 'assets#make_graphgist_disabled', as: :make_graphgist_disabled
  post 'candidates/graphgist/:id/status/candidate' => 'assets#make_graphgist_candidate', as: :make_graphgist_candidate
  post 'candidates/graphgist/:id/as_guide' => 'assets#make_graphgist_as_guide', as: :make_graphgist_as_guide
  post 'candidates/graphgist/:id/not_guide' => 'assets#make_graphgist_not_guide', as: :make_graphgist_not_guide

  get 'graph_gists/:id/recommendations.json' => 'info#graphgist_recommendations'

  get 'live_graphgists(.:format)' => 'info#live_graphgists'
  get 'graph_gists/.json' => 'graph_starter/assets#show'
  get 'graph_gists.json' => 'info#index_json'
  get 'graph_guides(.:format)' => 'info#graph_guides', as: :graph_guides

  get 'graph_gists/query_session_id' => 'query#graph_gist_query_session_id'
  post 'graph_gists/:graphgist_id/query' => 'query#graph_gist_query'

  get 'graph_gists/search/:query.json' => 'assets#search', as: :search
  get 'graph_gists/search_by_title_category_and_author/:query.json' => 'assets#search_by_title_category_and_author', as: :search_by_title_category_and_author

  get 'render_graphgist_js' => 'info#render_graphgist_js'

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}

  get 'challenges/new' => 'assets#challenge_new'
  post 'challenges' => 'assets#challenge_create', as: :challenge_create

  get 'categories/:slug(.:format)' => 'categories#show'
  get 'models/:name' => 'models#show', as: :model
  get 'authorizables/user_and_group_search.json' => 'authorizables#user_and_group_search'
  get ':model_slug/new' => 'assets#new', as: :new_asset
  get ':model_slug' => 'assets#index', as: :assets
  post ':model_slug' => 'assets#create', as: :create_asset
  get ':model_slug/:id(.:format)' => 'assets#show', as: :asset
  get ':model_slug/:id/edit' => 'assets#edit', as: :edit
  patch ':model_slug/:id' => 'assets#update'
  mount GraphStarter::Engine, at: '/'
end

app/controllers/assets_controller.rb
class AssetsController < ::GraphStarter::AssetsController

  def index
    super
    @assets.sort! { |a, b| [b.avg_rating, a.title] <=> [a.avg_rating, b.title] } if @assets.all? &.is_a?(GraphGist)
  end

  def search
    params.permit!

    query_string = params[:query]
    params[:model_slug] = "graph_gists"

    assets_ids = []
    assets_query = Neo4j::ActiveBase.current_session.query(
      "MATCH (asset:GraphGist {status:'live'}) "\
      "WHERE asset.title =~ {query} "\
      "RETURN asset.uuid AS id "\
      "LIMIT 30 "\
      "UNION "\
      "MATCH (asset:GraphGist {status:'live'})-[:FOR_INDUSTRY|:FOR_USE_CASE]->(category) "\
      "WHERE category.name =~ {query} "\
      "RETURN asset.uuid AS id "\
      "LIMIT 30 "\
      "UNION "\
      "MATCH (asset:GraphGist {status:'live'})<-[:WROTE]-(author:Person) "\
      "WHERE author.name =~ {query} "\
      "RETURN asset.uuid AS id "\
      "LIMIT 30",
    query: "(?i).*#{query_string}.*")

    assets_query.each do |asset|
      assets_ids.push(asset.id)
    end

    assets = GraphGist
      .query_as(:asset)
      .where("asset.uuid IN {ids}")
      .params(ids: assets_ids)
      .with(:asset)
      .optional_match('(asset)-[:HAS_IMAGE]->(image)')
      .pluck('asset {.title, .uuid, image: head(collect(image))}')

    results_data = assets.map do |asset|
      description = model_class.search_properties.map do |property|
        "<b>#{property.to_s.humanize}:</b> #{asset[property]}"
      end.join("<br>")

      first_image = asset[:image] ? asset[:image].source_url : nil

      {
        title: asset[:title],
        url: asset_path(id: asset[:uuid], model_slug: model_class.model_slug),
        description: description,
        image: first_image
      }.reject {|_, v| v.nil? }.tap do |result|
        model_class.search_properties.each do |property|
          result[property] = asset[property]
        end
      end
    end

    render json: {results: results_data}.to_json
  end

  def search_by_title_category_and_author
    params.permit!
    query_string = params[:query]
    params[:model_slug] = "graph_gists"

    assets_ids = []
    assets_query = Neo4j::ActiveBase.current_session.query(
      "MATCH (asset:GraphGist {status:'live'}) "\
      "WHERE asset.title =~ {query} "\
      "RETURN asset.uuid AS id "\
      "LIMIT 30 "\
      "UNION "\
      "MATCH (asset:GraphGist {status:'live'})-[:FOR_INDUSTRY|:FOR_USE_CASE]->(category) "\
      "WHERE category.name =~ {query} "\
      "RETURN asset.uuid AS id "\
      "LIMIT 30 "\
      "UNION "\
      "MATCH (asset:GraphGist {status:'live'})<-[:WROTE]-(author:Person) "\
      "WHERE author.name =~ {query} "\
      "RETURN asset.uuid AS id "\
      "LIMIT 30",
    query: "(?i).*#{query_string}.*")

    assets_query.each do |asset|
      assets_ids.push(asset.id)
    end

    assets = GraphGist
      .query_as(:asset)
      .where("asset.uuid IN {ids}")
      .params(ids: assets_ids)
      .with('asset')
      .optional_match('(asset)-[:HAS_IMAGE]->(image)')
      .with('asset, image')
      .optional_match('(asset)<-[:WROTE]-(author:Person)')
      .with('asset, image, author')
      .optional_match('(asset)-[:FOR_INDUSTRY]->(industry:Industry)')
      .with('asset, image, author, industry')
      .optional_match('(industry)-[:HAS_IMAGE]->(industry_image)')
      .with('asset, image, author, industry, head(collect(industry_image)) AS industry_image')
      .optional_match('(asset)-[:FOR_USE_CASE]->(use_case:UseCase)')
      .with('asset, image, author, industry, industry_image, use_case')
      .optional_match('(use_case)-[:HAS_IMAGE]->(use_case_image)')
      .with('asset, image, author, industry, industry_image, use_case, head(collect(use_case_image)) AS use_case_image')
      .pluck('asset {'\
        '.title,'\
        '.uuid,'\
        '.slug,'\
        '.updated_at,'\
        '.featured,'\
        '.created_at,'\
        '.neo4j_version,'\
        'author: author {.uuid, .name, .slug},'\
        'image: head(collect(image)),'\
        'industries: collect(industry {.uuid, .name, .slug, image: industry_image}),'\
        'use_cases: collect(use_case {.uuid, .name, .slug, image: use_case_image})'\
      '}')

    results_data = assets.map do |asset|
      first_image = asset[:image] ? asset[:image].source_url : nil

      {
        title: asset[:title],
        name: asset[:title],
        id: asset[:uuid],
        slug: asset[:slug],
        model_slug: params[:model_slug],
        neo4j_version: asset[:neo4j_version],
        updated_at: asset[:updated_at],
        created_at: asset[:created_at],
        featured: asset[:featured],
        image: first_image,
        author: asset[:author] ? {
          model_slug: 'people',
          name: asset[:author][:name],
          title: asset[:author][:name],
          id: asset[:author][:uuid],
        } : nil,
        industries: asset[:industries].map do |category|
          category_first_image = category[:image] ? category[:image].source_url : nil

          {
            title: category[:name],
            name: category[:name],
            id: category[:uuid],
            slug: category[:slug],
            model_slug: 'industries',
            image: category_first_image
          }
        end,
        use_cases: asset[:use_cases].map do |category|
          category_first_image = category[:image] ? category[:image].source_url : nil

          {
            title: category[:name],
            name: category[:name],
            id: category[:uuid],
            slug: category[:slug],
            model_slug: 'use_cases',
            image: category_first_image
          }
        end
      }
    end

    render json: results_data.to_json
  end

  def asset
    params.permit!
    super
  end

  def create
    params.permit!
    super
  end

  def rate
    params.permit!
    super
  end

  def asset_set(var = :asset, limit = 30)
    params.permit!
    super
  end

  def update
    params.permit!

    @asset = asset
    @asset.update(params[params[:model_slug].singularize])

    if params[:image].present?
      if @asset.class.has_image?
        @asset.image = Image.create(source: params[:image])
      elsif @asset.class.has_images?
        @asset.images << Image.create(source: params[:image])
      end
    end

    redirect_to action: :show, id: @asset.id
  end

  def show
    @asset, @access_level = asset_with_access_level

    if @asset
      @title = @asset.title

      # Don't wait
      Thread.new do
        View.record_view(session_node,
                         @asset,
                         browser_string: request.env['HTTP_USER_AGENT'],
                         ip_address: request.remote_ip)
        puts 'ending view thread'
      end
    else
      render file: 'public/404.html', status: :not_found, layout: false
    end
  end

  def show_source
    params[:model_slug] = "graph_gists"
    @asset, _ = asset_with_access_level

    render file: 'public/404.html', status: :not_found, layout: false unless @asset
  end

  def edit_graph_gists_by_owner
    params.permit!
    params[:model_slug] = "graph_gists"
    @liveAsset, @access_level = asset_with_access_level

    if @access_level != 'write'
      fail 'You don\'t have write access'
    end

    if !current_user.admin?
      @asset = GraphGistCandidate.where(graphgist:  @liveAsset).to_a[0]
      if !@asset
        @asset = GraphGistCandidate.create_from_graphgist(@liveAsset)
      end
    else
      @asset = @liveAsset
    end

    @title = @asset.title.to_s + ' - Edit'

    render file: 'public/404.html', status: :not_found, layout: false if !@asset
  end

  def update_graph_gists_by_owner
    params.permit!
    params[:model_slug] = "graph_gists"
    @liveAsset, @access_level = asset_with_access_level

    if @access_level != 'write'
      fail 'You don\'t have write access'
    end

    if !current_user.admin?
      @asset = @liveAsset.candidate
    else
      @asset = @liveAsset
      @candidate = @liveAsset.candidate
    end

    if current_user.admin?
      updateParams = params['graph_gist_candidate']
      updateParams = updateParams.merge(params['graph_gist'])
    else
      updateParams = params['graph_gist_candidate']
    end

    @asset.has_errors = false
    if !@asset.update(updateParams)
      flash[:error] = @asset.errors.messages.to_a.map {|pair| pair.join(' ') }.join(' / ')
      return redirect_to :back
    end

    if current_user.admin? and params[:image].present?
      if @asset.class.has_image?
        @asset.image = GraphStarter::Image.create(source: params[:image])
      elsif @asset.class.has_images?
        @asset.images << GraphStarter::Image.create(source: params[:image])
      end
    end
    
    if current_user.admin?
      @candidate.has_errors = false
      @candidate.update(updateParams)
    end

    if !current_user.admin?
      if ['candidate', 'draft'].include?(@liveAsset.status)
        @liveAsset.is_candidate_updated = false
        @liveAsset.update(params['graph_gist_candidate'])
      else
        @liveAsset.is_candidate_updated = true
        @liveAsset.save
      end
    end

    redirect_to graph_edit_by_owner_step2_path(id: params[:id])
  end

  def edit_graph_gists_by_owner_step2
    params.permit!
    params[:model_slug] = "graph_gists"
    @liveAsset, @access_level = asset_with_access_level

    if @access_level != 'write'
      fail 'You don\'t have write access'
    end

    if !current_user.admin?
      @asset = GraphGistCandidate.where(graphgist:  @liveAsset).to_a[0]
      if !@asset
        @asset = GraphGistCandidate.create_from_graphgist(@liveAsset)
      end
    else
      @asset = @liveAsset
    end

    @title = @asset.title.to_s + ' - Edit'

    render file: 'public/404.html', status: :not_found, layout: false if !@asset
  end

  def update_graph_gists_by_owner_step2
    params.permit!
    params[:model_slug] = "graph_gists"
    @liveAsset, @access_level = asset_with_access_level

    if @access_level != 'write'

app/views/graph_starter/assets/_admin_buttons.html.slim
- if asset.is_a?(GraphGistCandidate) || asset.is_a?(GraphGist)
  .ui.divider

  - if asset.status != 'live' && asset.status != 'draft'
    = form_tag make_graphgist_live_path(id: asset.is_a?(GraphGistCandidate) ? asset.graphgist.id : asset.id)
      button.ui.labeled.icon.button.teal type="submit"
        i.checkmark.icon
        | Approve
    .ui.divider

  = form_tag make_graphgist_disabled_path(id: asset.is_a?(GraphGistCandidate) ? asset.graphgist.id : asset.id)
    button.ui.labeled.icon.button type="submit"
      i.remove.circle.icon
      | Disable

- if asset.persisted?
  .ui.divider

  a.ui.labeled.icon.button href="#{graph_starter.edit_asset_path(id: @asset.id)}"
    i.edit.icon
    | Edit Metadata

  .ui.divider

  .ui.buttons
    a.ui.labeled.icon.red.button.right.floated href="#{graph_starter.destroy_asset_path(id: @asset.id)}"
      i.delete.icon
      | Delete

app/views/graph_starter/assets/_associations.html.slim
- as_cards = false if !defined?(as_cards)

- asset.class.authorized_associations.each do |name, association|
  - if association.target_class.ancestors.include?(GraphStarter::Asset)
    - result = asset.send(name)
    - result = result.to_a.sort! {|a, b| [b.avg_rating, a.title] <=> [a.avg_rating, b.title]} if association.target_class == GraphGist || association.target_class == GraphGistCandidate
    - if result.present?
      .item
        .content
          .ui.horizontal.divider = name.to_s.humanize
          .description
            - if as_cards
              .ui.link.cards
                - Array(result).each do |object|
                  = render partial: '/graph_starter/assets/card', locals: {asset: object}
            - else
              .ui.middle.aligned.big.divided.list
                - Array(result).each do |object|
                  .item
                    .content
                      = asset_icon object
                      = link_to object.title, asset_path(object)

app/views/graph_starter/assets/_card.html.slim
.card
  .content
    - if asset.private?
      .right.floated.meta
        i.hide.large.red.icon
    .header = link_to asset.safe_title, asset_path(asset)
  - if asset.class.has_images? || asset.class.has_image?
    .image
      - if asset.first_image_source_url.present?
        = image_tag asset.first_image_source_url
      - else
        = missing_image_tag
  - categories = Array(asset.categories).sort_by(&:name)
  - categories = categories.select{|c| c.is_a?(Person)} | categories
  = render partial: 'graph_starter/assets/extra_card_content', locals: {asset: asset}
  - if categories.present?
    .content
      .ui.relaxed.divided.list
        - categories[0, 2].each do |category|
          .item
            = asset_icon(category, (@category_images || {})[category.id])

            .content = link_to category.safe_title, asset_path(category)

        - if categories.size > 2
          .item
            i.ellipsis.horizontal.large.icon
            .content more categories

app/views/graph_starter/assets/_challenge_form.html.slim
- if request.post? || request.put?
  - if !@asset.valid?
    .ui.error.message
      i.close.icon
      ui.list
        - @asset.errors.messages.each do |field, errors|
          - errors.each do |error|
            li #{field} #{error}

= form_for @asset, url: challenge_create_path, html: {class: 'ui form', multipart: true} do |f|
  = render partial: 'images', locals: {asset: @asset}

  - if @access_level == 'write'
    .field
      label Add image

      = file_field_tag 'image'

  .field
    label Summary
    = f.text_area :summary

  .field
    label = 'Name'
    - id = SecureRandom.uuid
    - value = @asset.read_attribute('start_date')
    = f.text_field 'name', value: value, id: id

  .field
    label = 'Start date'
    i.calendar.icon
    i.wait.icon 
    - strftime_format = '%Y-%m-%d %H:%M'
    - id = SecureRandom.uuid
    - value = @asset.read_attribute('start_date')
    = f.text_field 'start_date', value: value && value.strftime(strftime_format), id: id, placeholder: "Format: YYYY-MM-DD HH:MM, always in UTC"
    - js_options = "format:'Y-m-d H:i'"
    javascript:
      $(function(){
        $('##{id}').datetimepicker({#{js_options.html_safe}});
      });

  .field
    label = 'End date'
    i.calendar.icon
    i.wait.icon 
    - strftime_format = '%Y-%m-%d %H:%M'
    - id = SecureRandom.uuid
    - value = @asset.read_attribute('end_date')
    = f.text_field 'end_date', value: value && value.strftime(strftime_format), id: id, placeholder: "Format: YYYY-MM-DD HH:MM, always in UTC"
    - js_options = "format:'Y-m-d H:i'"
    javascript:
      $(function(){
        $('##{id}').datetimepicker({#{js_options.html_safe}});
      });

  - @asset.class.authorized_associations.each do |name, association|
    - target_class = association.target_class
    - next if !target_class.ancestors.include?(GraphStarter::Asset)
    javascript:
      var current_#{name} = [];

    .field
      label = name.to_s.humanize

      - field_name = (association.type == :has_many ? "#{name.to_s.singularize}_ids" : "#{name}_id")
      - options = target_class.as(:n).pluck(target_class.name_property, target_class.id_property_name).map {|title, _| [GraphStarter::Asset.sanitize_title(title), _] }.sort_by {|pair| pair.inspect.downcase }

      - html_options = {class: 'ui fluid search dropdown'}
      - html_options[:multiple] = '' if association.type == :has_many
      = f.select field_name, options, {include_blank: 'Please select'}, html_options

  javascript:
    $(function(){
      $('.ui.dropdown').dropdown();
    });

  = f.submit 'Create', class: 'ui button'

app/views/graph_starter/assets/_extra_buttons.html.slim
- if asset.is_a?(GraphGistCandidate) || asset.is_a?(GraphGist)
  .ui.divider

  a onclick="$('#graph-guide-modal').modal('show')" href="#" Run this gist in the Neo4j console

  - if @asset.persisted?
    - if @access_level == 'write'
      .ui.divider
      div
        a.ui.labeled.icon.button href="#{graph_edit_by_owner_path(id: asset.is_a?(GraphGist) ? @asset.id : @asset.graphgist.id)}"
          i.edit.icon
          | Edit Graphgist
      - if asset.is_guide == false
        .ui.divider
        = form_tag make_graphgist_as_guide_path(id: asset.is_a?(GraphGistCandidate) ? asset.graphgist.id : asset.id)
          button.ui.button type="submit"
            | Optimized as Guide
      - if asset.is_guide == true
        .ui.divider
        p
          | This is optimized as Guide
        = form_tag make_graphgist_not_guide_path(id: asset.is_a?(GraphGistCandidate) ? asset.graphgist.id : asset.id)
          button.ui.button type="submit"
            | Remove from guides
      - if asset.status == 'draft'
        .ui.divider
        = form_tag make_graphgist_candidate_path(id: asset.is_a?(GraphGistCandidate) ? asset.graphgist.id : asset.id)
          button.ui.button type="submit"
            | Submit for Approval
      - if asset.status == 'candidate'
        .ui.divider
        div
          | Submitted for approval
      .ui.divider
      div
        | If approved, your graphgist will appear on the Neo4j.com/graphgists. You can make edits at any time, and when you are ready for the edits to appear on the Neo4j.com/graphgists you can submit again
    .ui.divider
    div
      a.ui.labeled.icon.button href="#{graph_show_source_path(id: asset.is_a?(GraphGist) ? @asset.id : @asset.graphgist.id)}"
        i.file.text.icon
        | Show Source

  .ui.modal#graph-guide-modal
    i.close.icon
    .header Play this GraphGist in your Neo4j console
    .content
      p Run this line in your Neo4j web console:

      pre style="white-space: pre-wrap; word-wrap: break-word"
        | :play
        = main_app.graph_guide_url(id_or_slug: @asset.slug)

      p You will likely need to configure your whitelist in Neo4j:

      h3 Neo4j 3.0

      pre style="white-space: pre-wrap; word-wrap: break-word"
        | browser.remote_content_hostname_whitelist=http://#{request.host}

      h3 Before Neo4j 3.0

      pre style="white-space: pre-wrap; word-wrap: break-word"
        | dbms.browser.remote_content_hostname_whitelist="http://#{request.host}"

app/views/graph_starter/assets/_extra_card_content.html.slim
- if asset.is_a?(GraphGist) && asset.featured? && !@featured_page
  .content
    i.large.thumbs.up.icon
    | Featured by the Neo Team

app/views/graph_starter/assets/_form.html.slim
- if action == 'update' || (request.post? || request.put?)
  - if !@asset.valid?
    .ui.error.message
      i.close.icon
      ui.list
        - @asset.errors.messages.each do |field, errors|
          - errors.each do |error|
            li #{field} #{error}

= form_for @asset, url: url_for(action: action), html: {class: 'ui form', multipart: true} do |f|
  = render partial: 'images', locals: {asset: @asset}

  - if @access_level == 'write'
    .field
      label Add image

      = file_field_tag 'image'

  .field
    label Summary

    = f.text_area :summary

  - @asset.class.authorized_properties_and_levels(current_user).each do |property, level|
    .field
      - editable_properties = GraphStarter.configuration.editable_properties[@asset.class.name.to_sym]
      - can_write = (level == 'write') && !f.nil? && (editable_properties.nil? || editable_properties.map(&:to_s).include?(property.name))

      - if @asset.class.display_property?(property.name) || can_write
        label = property.name.humanize

        = render partial: 'graph_starter/properties/property', locals: {property: property, asset: @asset, form: f, can_write: can_write}

  - @asset.class.authorized_associations.each do |name, association|
    - target_class = association.target_class
    - next if !target_class.ancestors.include?(GraphStarter::Asset)
    javascript:
      var current_#{name} = [];

    .field
      label = name.to_s.humanize

      - field_name = (association.type == :has_many ? "#{name.to_s.singularize}_ids" : "#{name}_id")
      - options = target_class.as(:n).pluck(target_class.name_property, target_class.id_property_name).map {|title, _| [GraphStarter::Asset.sanitize_title(title), _] }.sort_by {|pair| pair.inspect.downcase }

      - html_options = {class: 'ui fluid search dropdown'}
      - html_options[:multiple] = '' if association.type == :has_many
      = f.select field_name, options, {include_blank: 'Please select'}, html_options

  javascript:
    $(function(){
      $('.ui.dropdown').dropdown();
    });

  = f.submit action.humanize, class: 'ui button'

app/views/graph_starter/assets/challenge_new.html.slim
= javascript_include_tag 'jquery.datetimepicker', 'data-turbolinks-track' => true
= stylesheet_link_tag    'jquery.datetimepicker', media: 'all', 'data-turbolinks-track' => true

= render partial: 'challenge_form'

app/views/graph_starter/assets/new.html.slim
= javascript_include_tag 'jquery.datetimepicker', 'data-turbolinks-track' => true
= stylesheet_link_tag    'jquery.datetimepicker', media: 'all', 'data-turbolinks-track' => true

= render partial: 'form', locals: {action: 'create'}

app/views/graph_starter/assets/show.html.slim
javascript:
  var asset_id = '#{@asset.id}';
  var model_slug = '#{@asset.class.model_slug}';

- present_asset(@asset) do |asset_presenter|
  .ui.huge.centered.header
    .content
      = @asset.safe_title

  - if @asset.is_a?(GraphGist)
    - if @asset.status == 'candidate'
      .ui.message.yellow.gist-alert
        div.header This is an unapproved candidate.

  - if (@asset.is_a?(GraphGist) || @asset.is_a?(GraphGistCandidate)) && @asset.has_errors
    .ui.message.red.gist-alert
      div.header This graphgist has errors

  - center_width, right_width = "thirteen", "three"

  .ui.grid
    - if asset_presenter.main_column_exists?
      div class="#{center_width} wide column"
        - if @asset.summary.present?
          .ui.horizontal.divider Summary
          = simple_format @asset.summary
        - if asset_presenter.associations_in_body?
          = render partial: '/graph_starter/assets/associations', locals: {asset: @asset, as_cards: true}
        - else
          = render_body(@asset, @model_slug)

    div class="#{right_width} wide column" id="right-column"
      - if @asset.is_a?(GraphGist) && @asset.status == 'live'
          a href="https://neo4j.com/graphgist/#{@asset.id}"
            | Live Version

      - if @access_level == 'write' && (@asset.is_a?(GraphGistCandidate) || @asset.is_a?(GraphGist))
        - if @asset.is_a?(GraphGistCandidate) && @asset.graphgist.status == 'live'
          p
            a.ui.red.label href="#{graph_starter.asset_path(id: @asset.graphgist.id, model_slug: 'graph_gists')}"
              | Go to live version.

        - if @asset.is_a?(GraphGist) && @asset.is_candidate_updated
          p
            a.ui.red.label href="#{graph_starter.asset_path(id: @asset.candidate.id, model_slug: 'graph_gist_candidates')}"
              | This version is outdated.
              br
              | Go to candidate version.

        div.ui.label class=[@asset.status == 'candidate' ? "orange" : nil, @asset.status == 'live' ? "teal" : nil, @asset.status == 'disabled' ? "red" : nil]
          = @asset.status

      - if app_user_is_admin?
        = render partial: '/graph_starter/assets/admin_buttons', locals: {asset: @asset}
        = render partial: '/graph_starter/assets/extra_admin_buttons', locals: {asset: @asset}

      = render partial: '/graph_starter/assets/extra_buttons', locals: {asset: @asset}

      - if !asset_presenter.left_sidebar_exists? || @asset.is_a?(GraphGistCandidate)
        .ui.items
          - if !asset_presenter.associations_in_body?
            = render partial: '/graph_starter/assets/associations', locals: {asset: @asset}
          = render partial: '/graph_starter/assets/recommendations', locals: {asset: @asset}

      = render partial: '/graph_starter/assets/property_items', locals: {asset: @asset}