config/routes.rb
Rails.application.routes.draw do
  # constraints(host: /graphgist-portal.herokuapp.com/) do
  #   match '/(*path)' => redirect { |params, _req| "http://portal.graphgist.org/#{params[:path]}" }, via: [:get, :post]
  # end

  mathjax 'mathjax'

  root 'info#home'
  get 'about' => 'info#about'

  get 'featured_graphgists.json' => 'info#featured_graphgists_json'
  get 'featured_graphgists(.:format)' => 'info#featured_graphgists'

  get 'submit_graphgist' => 'info#submit_graphgist'

  get 'submit_challenge_entry' => 'info#submit_challenge_entry'

  post 'preview_graphgist' => 'info#preview_graphgist'
  get 'preview_graphgist/:id' => 'info#preview_graphgist'
  patch 'preview_graphgist/:id' => 'info#preview_graphgist'

  get 'monitor' => 'info#monitor'

  authenticated do
    post 'create_graphgist' => 'info#create_graphgist'
    get 'my_graphgists' => 'info#my_graphgists'
  end

  get 'challenge_graphgists' => 'info#challenge_graphgists'

  get 'render_graphgist' => 'info#render_graphgist'

  get 'graph_gists/by_graphgist_id/*id(.:format)' => 'info#show_from_graphgist_id'
  get 'graph_gists/by_graphgist_id(.:format)' => 'info#show_from_graphgist_id'
  get 'graph_gists/by_url' => 'info#show_from_url'
  get 'graph_gists/new' => redirect('submit_graphgist')
  # Deprecated:
  get 'show_from_graphgist_id/:id(.:format)' => 'info#show_from_graphgist_id'

  match 'graph_gists/:id_or_slug/graph_guide' => 'info#graph_guide_options', via: :options
  get 'graph_gists/:id_or_slug/graph_guide' => 'info#graph_guide', as: :graph_guide

  get 'graph_gists/:id/edit_by_owner' => 'assets#edit_graph_gists_by_owner', as: :graph_edit_by_owner
  patch 'graph_gists/:id/edit_by_owner' => 'assets#update_graph_gists_by_owner', as: :graph_update_by_owner

  get 'graph_gists/:id/edit_by_owner_step2' => 'assets#edit_graph_gists_by_owner_step2', as: :graph_edit_by_owner_step2
  patch 'graph_gists/:id/edit_by_owner_step2' => 'assets#update_graph_gists_by_owner_step2', as: :graph_update_by_owner_step2

  get 'graph_gists/:id/source' => 'assets#show_source', as: :graph_show_source

  get 'candidates/waiting_review' => 'info#list_candidates', as: :list_candidates_graphgist
  post 'candidates/graphgist/:id/status/live' => 'assets#make_graphgist_live', as: :make_graphgist_live
  post 'candidates/graphgist/:id/status/disabled' => 'assets#make_graphgist_disabled', as: :make_graphgist_disabled
  post 'candidates/graphgist/:id/status/candidate' => 'assets#make_graphgist_candidate', as: :make_graphgist_candidate
  post 'candidates/graphgist/:id/as_guide' => 'assets#make_graphgist_as_guide', as: :make_graphgist_as_guide
  post 'candidates/graphgist/:id/not_guide' => 'assets#make_graphgist_not_guide', as: :make_graphgist_not_guide

  get 'graph_gists/:id/recommendations.json' => 'info#graphgist_recommendations'

  get 'live_graphgists(.:format)' => 'info#live_graphgists'
  get 'graph_gists/.json' => 'graph_starter/assets#show'
  get 'graph_gists.json' => 'info#index_json'
  get 'graph_guides(.:format)' => 'info#graph_guides', as: :graph_guides

  get 'graph_gists/query_session_id' => 'query#graph_gist_query_session_id'
  post 'graph_gists/:graphgist_id/query' => 'query#graph_gist_query'

  get 'graph_gists/search/:query.json' => 'assets#search', as: :search
  get 'graph_gists/search_by_title_category_and_author/:query.json' => 'assets#search_by_title_category_and_author', as: :search_by_title_category_and_author

  get 'render_graphgist_js' => 'info#render_graphgist_js'

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations', omniauth_callbacks: 'users/omniauth_callbacks'}

  get 'challenges/new' => 'assets#challenge_new'
  post 'challenges' => 'assets#challenge_create', as: :challenge_create

  get 'categories/:slug(.:format)' => 'categories#show'
  get 'models/:name' => 'models#show', as: :model
  get 'authorizables/user_and_group_search.json' => 'authorizables#user_and_group_search'
  get ':model_slug/new' => 'assets#new', as: :new_asset
  get ':model_slug' => 'assets#index', as: :assets
  post ':model_slug' => 'assets#create', as: :create_asset
  get ':model_slug/:id(.:format)' => 'assets#show', as: :asset
  get ':model_slug/:id/edit' => 'assets#edit', as: :edit
  patch ':model_slug/:id' => 'assets#update'
  mount GraphStarter::Engine, at: '/'
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
  before_action :authenticate_user!, :only => [:submit_graphgist, :my_graphgists, :create_graphgist]

  def featured_graphgists
    @title = 'Featured GraphGists'

    @featured_graphgists = apply_associations(GraphGist.only_featured.limit(30)).to_a

    @featured_page = true
  end

  def index_json
    params.permit!
    assets = GraphGist
      .query_as(:asset)
      .where('asset.status = "live"')

    if params[:category].present?
      assets = assets
        .match('(asset)-[:FOR_INDUSTRY|:FOR_USE_CASE]->(category)')
        .where('category.slug = {slug}')
        .params(slug: params[:category])
    end

    if params[:author].present?
      assets = assets
        .match('(asset)<-[:WROTE]-(author:Person)')
        .where('author.slug = {slug} OR author.uuid = {slug}')
        .params(slug: params[:author])
    end

    list_json(assets)
  end

  def featured_graphgists_json
    assets = GraphGist
      .query_as(:asset)
      .where("asset.featured = true")

    list_json(assets)
  end

  def list_json(assets)
    assets = assets
      .with('asset')
      .limit(30)
      .optional_match('(asset)-[:HAS_IMAGE]->(image:Image)')
      .with('asset, image')
      .optional_match('(asset)<-[:WROTE]-(author:Person)')
      .with('asset, image, author')
      .optional_match('(asset)-[:FOR_INDUSTRY]->(industry:Industry)')
      .with('asset, image, author, industry')
      .optional_match('(industry)-[:HAS_IMAGE]->(industry_image)')
      .with('asset, image, author, industry, head(collect(industry_image)) AS industry_image')
      .optional_match('(asset)-[:FOR_USE_CASE]->(use_case:UseCase)')
      .with('asset, image, author, industry, industry_image, use_case')
      .optional_match('(use_case)-[:HAS_IMAGE]->(use_case_image)')
      .with('asset, image, author, industry, industry_image, use_case, head(collect(use_case_image)) AS use_case_image')
      .pluck('asset {'\
        '.title,'\
        '.uuid,'\
        '.slug,'\
        '.summary,'\
        '.updated_at,'\
        '.featured,'\
        '.created_at,'\
        '.neo4j_version,'\
        'author: author {.uuid, .name, .slug},'\
        'image: head(collect(image)),'\
        'industries: collect(distinct industry {.uuid, .name, .slug, image: industry_image}),'\
        'use_cases: collect(distinct use_case {.uuid, .name, .slug, image: use_case_image})'\
      '}')

    assets_result = assets.map do |asset|
      author = asset[:author]
      first_image = asset[:image] ? asset[:image].source_url : nil

      {
        title: asset[:title],
        name: asset[:title],
        summary: asset[:summary],
        neo4j_version: asset[:neo4j_version],
        id: asset[:uuid],
        slug: asset[:slug],
        model_slug: params[:model_slug],
        updated_at: asset[:updated_at],
        created_at: asset[:created_at],
        featured: asset[:featured],
        image: first_image,
        author: author ? {
          model_slug: 'people',
          name: author[:name],
          title: author[:name],
          id: author[:uuid],
        } : nil,
        industries: asset[:industries].map do |category|
          category_first_image = category[:image] ? category[:image].source_url : nil

          {
            title: category[:name],
            name: category[:name],
            id: category[:uuid],
            slug: category[:slug],
            model_slug: 'industries',
            image: category_first_image
          }
        end,
        use_cases: asset[:use_cases].map do |category|
          category_first_image = category[:image] ? category[:image].source_url : nil

          {
            title: category[:name],
            name: category[:name],
            id: category[:uuid],
            slug: category[:slug],
            model_slug: 'use_cases',
            image: category_first_image
          }
        end
      }
    end

    render json: assets_result.to_json
  end

  def live_graphgists
    @live_graphgists = apply_associations(GraphGist.only_live.for_category('asset', params[:category])).to_a
  end

  def graph_guides
    @assets = apply_associations(GraphGist.only_guide).to_a
  end

  def associations
    return @associations if @associations.present?

    @associations = []
    @associations << GraphGist.image_association
    @associations += GraphGist.category_associations
    @associations.compact!
    @associations
  end

  def apply_associations(scope, var = :asset)
    if associations.present?
      # Gah, shouldn't need this proxy_as business.  Bug to fix, I think...
      scope.query_as(var).with(var).proxy_as(GraphGist, var).with_associations(*associations)
    else
      scope
    end
  end

  def challenge_graphgists
    @graph_gists = GraphGist.as(:gist).challenge_category.pluck(:gist)
  end

  def home
    @title = 'Home'
  end

  def about
    @title = 'What is a GraphGist?'
  end

  def graphgist_recommendations
    graphgist = GraphGist.find(params[:id])

    @recommendations = graphgist.secret_sauce_recommendations
  end

  def submit_graphgist
    @title = 'Submit a GraphGist'
    @graphgist_template = File.read('config/graphgist_template.adoc')
  end

  def submit_challenge_entry
    @title = 'Submit a GraphGist'
  end

  def preview_graphgist
    params.permit!
    id = params[:id]

    if params[:graph_gist_candidate]
      url = params[:graph_gist_candidate][:url]
      asciidoc = params[:graph_gist_candidate][:asciidoc]
    elsif params[:graph_gist]
      url = params[:graph_gist][:url]
      asciidoc = params[:graph_gist][:asciidoc]
    end

    if id.present?
      begin
        @graphgist = GraphGistCandidate.find(id)
      rescue Neo4j::ActiveNode::Labels::RecordNotFound
        @graphgist = GraphGist.find(id)
      end
    else
      @graphgist = GraphGistCandidate.new(title: 'Preview')
    end

    if url.present?
      @graphgist.url = url
      @graphgist.place_current_url
    elsif asciidoc.present?
      @graphgist.asciidoc = asciidoc
      @graphgist.place_current_asciidoc
    end

    @hide_menu = true

    @no_ui_container = true
  end

  def add_credentials_to_url(url, username, password)
    URI(url).tap do |uri|
      uri.user = CGI.escape username
      uri.password = CGI.escape password
    end.to_s
  end

  def show_from_url
    @graphgist = GraphGist.new(url: params[:url], title: 'Preview')

    @graphgist.place_current_url

    @warn_of_preview = true

    render 'preview_graphgist'
  rescue GraphGistTools::InvalidGraphGistIDError => e
    render text: e.message, status: :bad_request
  end

  def show_from_graphgist_id
    @asset = GraphGist.from_graphgist_id(params[:id])

    @asset.place_current_url if @asset

    if @asset && @asset.valid?
      @model_slug = 'graph_gists'
      render 'graph_starter/assets/show'
    else
      render text: "Invalid GraphGist ID (#{@asset && @asset.errors.messages.inspect})", status: :bad_request
    end
  rescue GraphGistTools::InvalidGraphGistIDError => e
    render text: e.message, status: :bad_request
  end

  skip_before_action :verify_authenticity_token, only: :graph_guide_options
  def graph_guide_options
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Headers'] = 'Pragma,Cache-Control,If-Modified-Since,Content-Type,X-Requested-With,X-stream,X-Ajax-Browser-Auth'
    response.headers['Access-Control-Allow-Methods'] = 'GET'

    render text: ''
  end

  def graph_guide
    response.headers['Access-Control-Allow-Origin'] = '*'
    response.headers['Access-Control-Allow-Headers'] = 'Pragma,Cache-Control,If-Modified-Since,Content-Type,X-Requested-With,X-stream,X-Ajax-Browser-Auth'
    response.headers['Access-Control-Allow-Methods'] = 'GET'

    @graph_gist = GraphGist.as(:g).where('g.slug = {id_or_slug} OR g.uuid = {id_or_slug}', id_or_slug: params[:id_or_slug]).first

    render 'graph_guide', layout: false
  end

  def create_graphgist # rubocop: disable Metrics/AbcSize
    redirect_to '/' if !current_user.present?

    params.permit!

    url = params[:graph_gist][:url]
    if url.present? and GraphGist.find_by(url: url)
      return redirect_to submit_graphgist_path(url_used: 1)
    end

    Neo4j::ActiveBase.run_transaction do
      if url.empty?
        params[:graph_gist].delete :url
      end

      @graphgist = GraphGist.create(params[:graph_gist].except(:industries, :use_cases, :challenge_category).merge({
        author: current_user.person,
        creators: [current_user]
      }))

      unless @graphgist.errors.present?
        @candidate = GraphGistCandidate.create_from_graphgist(@graphgist)
      end
    end

    if @graphgist.errors.present?
      flash[:error] = @graphgist.errors.messages.to_a.map {|pair| pair.join(' ') }.join(' / ')
      return redirect_to submit_graphgist_path
    end

    redirect_to graph_edit_by_owner_step2_path(id: @graphgist.id)
  end

  def render_graphgist
    url = GraphGistTools.raw_url_for_graphgist_id(params[:id])
    @graphgist = GraphGist.new(url: url) if url.present?
  end

  def render_graphgist_js
    render layout: false
  end

  # For externally testing that the app is up
  def monitor
    if GraphGist.first
      render text: 'OK', status: :ok
    else
      render text: 'SERVICE UNAVAILABLE', status: :service_unavailable
    end
  end

  def list_candidates
    redirect_to '/' if !current_user.present? || !current_user.admin?

    @candidates = GraphGistCandidate.where(status: 'candidate')
  end

  def my_graphgists
    redirect_to '/' if !current_user.present?

    @title = 'My GraphGists'
    @graphgists = GraphGistCandidate.where(author: current_user.person)
  end
end

app/helpers/info_helper.rb
module InfoHelper
  ADOC_LOAD_OPTIONS = {
    attributes: ['experimental', 'env-guide'].freeze,
    header_footer: true,
    safe: 0,
    template_dir: Rails.root.join('graph_guide_templates').to_s
  }

  def graph_guide_parts_for(graph_gist)
    # html_doc = Nokogiri::HTML(graph_gist.html)
    # slide_level = (1..6).find { |i| html_doc.xpath("//h#{i}").size > 1 } - 1

    # Flatten headers
    adoc_text = graph_gist.asciidoc.gsub(/^=+ /, '== ')

    adoc = Asciidoctor.load(adoc_text, ADOC_LOAD_OPTIONS)

    if adoc.blocks[0] != adoc.sections[0]
      end_of_header_position = adoc_text.index(/(\r|\n|\r\n){2}/)
      spliced_text = adoc_text[0, end_of_header_position] + "\n\n== #{adoc.doctitle}" + adoc_text[end_of_header_position..-1]
      adoc = Asciidoctor.load(spliced_text, ADOC_LOAD_OPTIONS)
    end

    # adoc.convert # Why do I need to do this?  No idea...
    # adoc.set_attribute('slide_level', slide_level.to_s)
    adoc.convert
  end
end

app/views/info/_graphgist_submission.html.slim
= form_tag create_graphgist_path, id: "graph_gist_form"
  .ui.form method="get"
    .field#title-field
      label Title (Required)
      = text_field_tag 'graph_gist[title]', nil, required: true

    .field#asciidoc_field
      label AsciiDoc
      = text_area_tag 'graph_gist[asciidoc]', @graphgist_template

    .field#url_field
        label
          | or URL
          |  
          a#open-preview style="display: none; cursor: pointer" Open preview in new page
        = text_field_tag 'graph_gist[url]'

    = yield :graphgist_submission_form

    #preview-button.ui.button Preview

    button type="submit" name="graph_gist_candidate[status]" value="draft" id="save-button" class="ui primary button"
      | Save and Continue

    - if !current_user
      strong You will need to sign in with <a href="#{main_app.user_omniauth_authorize_path(:twitter)}">Twitter</a> or <a href="#{main_app.user_omniauth_authorize_path(:github)}">GitHub</a> to submit a GraphGist to the portal


#iframe-spinner.ui.active.centered.large.loader

coffee:
  $('#preview-button').click (e) ->
    e.preventDefault();
    form = $('#graph_gist_form');
    originalAction = form.attr('action');
    $('#iframe-spinner').show();

    form.attr('target', 'graph_gist_preview')
        .attr('novalidate', true)
        .attr('action', '/preview_graphgist')
        .submit()
        .removeAttr('target')
        .removeAttr('novalidate')
        .attr('action', originalAction);

  cm = CodeMirror.fromTextArea document.getElementById('graph_gist_asciidoc'),
    lineNumbers: true
    lineWrapping: true
    mode: 'asciidoc',
    theme: 'midnight',

  cm.on 'change', (instance, changeObj) ->
    if instance.getValue().replace(/\s+/, '').length > 0
      $('#url_field').addClass('disabled').find('input').val('')
    else
      $('#url_field').removeClass('disabled')

  window.iframe_loaded = ->
    $('#iframe-spinner').hide();

  $('#open-preview').click ->
    url = $('#graph_gist_url').val().replace(/^\s*/, '').replace(/\s+$/, '')

    window.open('/graph_gists/by_url?url=' + encodeURIComponent(url), '_blank')

  $('#graph_gist_url').keyup ->
    if $('#graph_gist_url').val().replace(/\s+/, '').length > 0
      cm.setValue ''
      cm.setOption 'readOnly', true
      $('#asciidoc_field').addClass('disabled')
      $('#open-preview').show()
    else
      cm.setOption 'readOnly', false
      $('#asciidoc_field').removeClass('disabled')
      $('#open-preview').hide()

  # $('#create-button').addClass 'disabled' if !current_user?

iframe onload="window.iframe_loaded()" name="graph_gist_preview"

scss:
  iframe {
    width: 100%;
    height: 1000px;
    margin-top: 1em;
    border: 1px solid #999;
  }

  #iframe-spinner {
    display: none;
    left: 45%;
    position: absolute;
    top: 60%;
  }

app/views/info/about.html.slim
scss:
  pre {
    background-color: #FDFFE8;
    border: 1px solid black;
    padding: 1em;
    font-size: 0.7em;
    display: inline-block;
    margin-right: 1em;
  }

div style="font-size: 1.4rem"

  h1 What is a GraphGist?

  = image_tag 'about_graphgists.png', class: 'ui right large floated image'

  p
    |
      With Neo4j GraphGists you can describe and model your domain in a simple text file (<a href="http://asciidoc.org/">AsciiDoc</a>) and render it as a rich, interactive, database-backed page in any browser.

      It is perfect to document a specific domain, use-case, question or graph problem.

  h2 Examples

  p GraphGists work like any AsciiDoc document, but they allow you to insert special comments to define how data from Neo4j can be displayed and interacted with.

  p First define a block of <a href="http://neo4j.com/developer/cypher-query-language/">Cypher</a> code to setup the database, this block can also use LOAD CSV. Please use a educational graph size (around 150 nodes and rels):

  pre
    |
      //setup
      //hide
      [source,cypher]
      ----
      CREATE (neo:Database {name:'Neo4j'})
      CREATE (neo)-[:SUPPORTS]->(:Language {name:'Cypher'})
      ----

  p You can then describe the use-cases, run their queries on the data and output results as a table and/or a graph:

  div
    pre style="float: left"
      |
        [source,cypher]
        ----
        MATCH (db:Database)-[:SUPPORTS]->(language:Language)
        RETURN db.name as db, collect(language.name) as languages
        ----

        //table

    pre
      |
        [source,cypher]
        ----
        MATCH (d:Database)-[rel:SUPPORTS]->(l:Language)
        RETURN d,l
        ----

        //graph_result


  p You can fork <a href="https://gist.github.com/jexp/a56f7e7587ce5ed97561">this GraphGist template</a> to have something to start working with.

  p
    |
      A reader can explore your GraphGist to read and understand your domain.  A live console is also inserted into GraphGists so that readers can even try out their own queries
      We want to encourage you to model a domain that you know or like and describe it interactively in a GraphGist.

  /p
    |
      To learn about interesting existing models created by other Neo4j users browse the <a href="http://neo4j.com/graphgists/">impressive collection</a>.

  h2 How do I create a GraphGist?

  asciidoc:
    . Find a great domain (Music, Dating, Comics, Healthcare, Politics, Sciences, ...)
    . Whiteboard a good example graph model.
    . Determine interesting use-cases.
    . Create Cypher statements for setup and query-use-cases.
    . Write a good description and create a useful model picture (using a tool like link:http://gliffy.com[Gliffy] or link:http://www.apcjones.com/arrows/#[Arrows] or Neo4j Browser).
    . Compose it all nicely in your AsciiDoc-GraphGist-file (see link:https://github.com/neo4j-contrib/graphgist/blob/master/gists/syntax.adoc[this syntax documentation]).
    . Store it as a link:https://gist.github.com/[GitHub Gist]
    . Submit the URL on the link:/submit_graphgist[submission page]

    link:http://player.vimeo.com/video/74279113?badge=0&byline=0&portrait=0&title=0[**Watch the video to learn more!**]

  /h2 GraphGist Challenges

  /p
    |
      There have been three GraphGist competitions so far.  Check out our most recent <a href="/challenge/index.html">2015/2016 Winter Challenge</a>!

  /p
    |
      The best way gathering great graph models is to ask your community.
      That's why we already ran several challenges to find interesting ideas for GraphGists with tremendous results.

  /p
    asciidoc:
      The first challenge in September 2013 had link:https://github.com/neo4j-contrib/graphgist/wiki#wiki-graphgist-september-challenge-submissions[17 submissions] and link:http://blog.neo4j.org/2013/10/the-first-graphgist-challenge-completed.html?_ga=1.56087459.909862480.1422364624[3 winners].

  /p
    asciidoc:
      Our GraphGist Winter Challenge (Dec 2013-Jan 2014) asked for contributions in 10 categories.
      We got an impressive link:https://github.com/neo4j-contrib/graphgist/wiki#wiki-graphgist-winter-challenge-submissions---categories[65 submissions]. Here are the link:http://blog.neo4j.org/2014/02/graph-gist-winter-challenge-winners.html?_ga=1.56087459.909862480.1422364624[winners per category]

  p

  p
  

app/views/info/challenge.html.slim
css:
  .ui.header {
    width: 100%;
  }

.ui.text.container
  .ui.middle.aligned.stackable.grid.container
    .row
      h2.ui.header GraphGist Winter Challenge 2015 / 2016


      p
        = image_tag 'challenge/star_wars_theme.png', class: 'ui centered medium right floated image'
        |
          This year, as you suffer through the long winter in the ice caves on Sloth, make sure to take care of those around you.
          Feed some hay to the tauntauns before they have to brave the cold for holiday deliveries.
          Convince a vicious wampa to go vegan.
          Skip a night patrol and do a little quiet thinking about all those wonderful data relationships in your life.

        br
        br

        |
          Oh yes, it’s that time of year again... the most wonderful time of the year... it’s time to enter this year’s Graphgist Challenge: May the Graph Be With You.
          This year the Neo4j Revolution—known across the galaxy as the DB Rebellion—is rewarding those who come up with the most ingenious graph models and queries in the galaxy.

      p This year we're focused on some of the uses cases that graph databases are best suited to handle:

      ul
        li Convert one star system’s complex <strong>relational models</strong> and queries to a graph model that works integrates seamlessly with the Rebellion’s apps.

        li Wish for galactic peace. <strong>Recommendations</strong> for anything imaginable

        li What if the Empire attacks the Rebellions subspace comms network? Perform <strong>Impact Analysis</strong> on dependent systems’ networks

        li A library of everything Rebellion. <strong>Content and asset management</strong>

        li Find another habitable planet to assemble forces for the next attack. Creative <strong>Graph Search and Insights</strong>

        li Discover new territories and quadrants - <strong>Give your best</strong> and show us a graph application beyond imagination

      p
        |
          Time is running short and your imagination may be our only hope for the Rebellion. 
          #{link_to 'Submit your Graphgist entries', submit_graphgist_path} by 6pm US Pacific time on January 4, 2016. 

      p
        |
          After determining the most illuminating and imaginative entries, the Planetary Lords will then announce the winners of this year’s Galactic Cup.
          <strong>For each of the categories there will a prize of a $500 Amazon gift card.</strong>

      p And don’t forget... when you use Neo4j, the Graph will be with you, always.

    .row
      h2 Categories

      .ui.relaxed.divided.list
        .item
          i.large.middle.aligned.book.icon
          .content Pop culture or literature
        .item
          i.large.middle.aligned.newspaper.icon
          .content Investigative journalism (Idea: “Be a Journalist - collect facts, draw connections gain insights”)
        .item
          i.large.middle.aligned.soccer.icon
          .content Sports (olympics)
        .item
          i.large.middle.aligned.world.icon
          .content Politics (e.g. Terrorism?, US elections) < Predict the 2016 D/R Nominees
        .item
          i.large.middle.aligned.gift.icon
          .content Holidays (cultural, gift-finder, holiday-themed movies, recipes...)
        .item
          i.large.middle.aligned.line.chart.icon
          .content Open / government data (public health, etc)
        .item
          i.large.middle.aligned.pie.chart.icon
          .content Mashups of public web APIs or public datasets (for some ideas check out <a href="https://github.com/caesar0301/awesome-public-datasets">Awesome Public Datasets</a> and <a href="https://tinyletter.com/data-is-plural">Data is Plural</a>)
        .item
          i.large.middle.aligned.spy.icon
          .content Plots or characters from movies or books


    .row
      h2.ui.header Judging

      p
        | Judging will be based on the following criteria:

        ul
          li Easy to understand description
          li Easy to understand model picture
          li Sensible dataset size (20-75 nodes)
          li Good use of the gist tools (table, graph, hide-setup etc)
          li A good number of realistic use-cases (at least 2 or 3) with sensible result output
          li An interesting / insightful subject domain
          li We had an epiphany while looking at the gist


      h3.ui.header The Judges

      p
        .ui.items
          .item 
            a.ui.tiny.image href="https://github.com/johnymontana"
              = image_tag 'challenge/judges/johnymontana.png'
            .middle.aligned.content
              .header William Lyon
          .item
            a.ui.tiny.image href="https://github.com/luanne" 
              = image_tag 'challenge/judges/luanne.png'
            .middle.aligned.content
              .header Luanne Misquitta
          .item
            a.ui.tiny.image href="https://github.com/nicolewhite/"
              = image_tag 'challenge/judges/nicolewhite.png'
            .middle.aligned.content
              .header Nicole White
          .item
            a.ui.tiny.image href="https://github.com/jjaderberg/"
              = image_tag 'challenge/judges/jjaderberg.png'
            .middle.aligned.content
              .header Jonatan Jäderberg
          .item
            a.ui.tiny.image href="https://twitter.com/kevinvangundy"
              = image_tag 'challenge/judges/kevinvangundy.png'
            .middle.aligned.content
              .header Kevin Van Gundy

    .row
      h2.ui.header Prizes

      ul
        li For each category there will be a prize of an $300 Amazon Gift Card

        li The top prize will be a $500 Amazon Gift Card

        li Each participant gets a Neo4j T-Shirt

app/views/info/challenge_graphgists.html.slim
= render partial: 'graph_starter/assets/cards', locals: {assets: @graph_gists}

app/views/info/featured_graphgists.html.slim
h1 Featured GraphGists

= render partial: 'graph_starter/assets/cards', locals: {assets: @featured_graphgists}

app/views/info/graph_guide.html.slim
html data-ember-extensions="1"
  body
    = graph_guide_parts_for(@graph_gist).html_safe